/*
 * Togai Apis
 * APIs for Togai App
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: engg@togai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.togai.core.service.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.togai.core.service.client.model.BundleStrategy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * RateCardBundle
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RateCardBundle implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * Gets or Sets rateStrategy
   */
  @JsonAdapter(RateStrategyEnum.Adapter.class)
  public enum RateStrategyEnum {
    FLAT("FLAT");

    private String value;

    RateStrategyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RateStrategyEnum fromValue(String value) {
      for (RateStrategyEnum b : RateStrategyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RateStrategyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RateStrategyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RateStrategyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RateStrategyEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_RATE_STRATEGY = "rateStrategy";
  @SerializedName(SERIALIZED_NAME_RATE_STRATEGY)
  private RateStrategyEnum rateStrategy;

  /**
   * Gets or Sets slabStrategy
   */
  @JsonAdapter(SlabStrategyEnum.Adapter.class)
  public enum SlabStrategyEnum {
    TIER("TIER");

    private String value;

    SlabStrategyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SlabStrategyEnum fromValue(String value) {
      for (SlabStrategyEnum b : SlabStrategyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SlabStrategyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SlabStrategyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SlabStrategyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SlabStrategyEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SLAB_STRATEGY = "slabStrategy";
  @SerializedName(SERIALIZED_NAME_SLAB_STRATEGY)
  private SlabStrategyEnum slabStrategy;

  public static final String SERIALIZED_NAME_BUNDLES = "bundles";
  @SerializedName(SERIALIZED_NAME_BUNDLES)
  private List<BundleStrategy> bundles = new ArrayList<>();

  public RateCardBundle() {
  }

  public RateCardBundle rateStrategy(RateStrategyEnum rateStrategy) {
    
    this.rateStrategy = rateStrategy;
    return this;
  }

   /**
   * Get rateStrategy
   * @return rateStrategy
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public RateStrategyEnum getRateStrategy() {
    return rateStrategy;
  }


  public void setRateStrategy(RateStrategyEnum rateStrategy) {
    this.rateStrategy = rateStrategy;
  }


  public RateCardBundle slabStrategy(SlabStrategyEnum slabStrategy) {
    
    this.slabStrategy = slabStrategy;
    return this;
  }

   /**
   * Get slabStrategy
   * @return slabStrategy
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public SlabStrategyEnum getSlabStrategy() {
    return slabStrategy;
  }


  public void setSlabStrategy(SlabStrategyEnum slabStrategy) {
    this.slabStrategy = slabStrategy;
  }


  public RateCardBundle bundles(List<BundleStrategy> bundles) {
    
    this.bundles = bundles;
    return this;
  }

  public RateCardBundle addBundlesItem(BundleStrategy bundlesItem) {
    this.bundles.add(bundlesItem);
    return this;
  }

   /**
   * Get bundles
   * @return bundles
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<BundleStrategy> getBundles() {
    return bundles;
  }


  public void setBundles(List<BundleStrategy> bundles) {
    this.bundles = bundles;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RateCardBundle rateCardBundle = (RateCardBundle) o;
    return Objects.equals(this.rateStrategy, rateCardBundle.rateStrategy) &&
        Objects.equals(this.slabStrategy, rateCardBundle.slabStrategy) &&
        Objects.equals(this.bundles, rateCardBundle.bundles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rateStrategy, slabStrategy, bundles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RateCardBundle {\n");
    sb.append("    rateStrategy: ").append(toIndentedString(rateStrategy)).append("\n");
    sb.append("    slabStrategy: ").append(toIndentedString(slabStrategy)).append("\n");
    sb.append("    bundles: ").append(toIndentedString(bundles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

