/*
 * Togai Apis
 * APIs for Togai App
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engg@togai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.togai.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.togai.client.models.PricePlanDetails;
import com.togai.client.models.RevenueInfo;
import com.togai.client.models.UsageLookupRange;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.togai.client.JSON;

/**
 * CalculateRevenueResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class CalculateRevenueResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  @javax.annotation.Nonnull
  private String currency;

  public static final String SERIALIZED_NAME_USAGE_LOOKUP_RANGE = "usageLookupRange";
  @SerializedName(SERIALIZED_NAME_USAGE_LOOKUP_RANGE)
  @javax.annotation.Nullable
  private UsageLookupRange usageLookupRange;

  public static final String SERIALIZED_NAME_PRICE_PLAN_DETAILS = "pricePlanDetails";
  @SerializedName(SERIALIZED_NAME_PRICE_PLAN_DETAILS)
  @javax.annotation.Nonnull
  private PricePlanDetails pricePlanDetails;

  public static final String SERIALIZED_NAME_REVENUE_INFO = "revenueInfo";
  @SerializedName(SERIALIZED_NAME_REVENUE_INFO)
  @javax.annotation.Nonnull
  private List<RevenueInfo> revenueInfo = new ArrayList<>();

  public CalculateRevenueResponse() {
  }

  public CalculateRevenueResponse currency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Get currency
   * @return currency
   */
  @javax.annotation.Nonnull
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(@javax.annotation.Nonnull String currency) {
    this.currency = currency;
  }


  public CalculateRevenueResponse usageLookupRange(@javax.annotation.Nullable UsageLookupRange usageLookupRange) {
    this.usageLookupRange = usageLookupRange;
    return this;
  }

  /**
   * Get usageLookupRange
   * @return usageLookupRange
   */
  @javax.annotation.Nullable
  public UsageLookupRange getUsageLookupRange() {
    return usageLookupRange;
  }

  public void setUsageLookupRange(@javax.annotation.Nullable UsageLookupRange usageLookupRange) {
    this.usageLookupRange = usageLookupRange;
  }


  public CalculateRevenueResponse pricePlanDetails(@javax.annotation.Nonnull PricePlanDetails pricePlanDetails) {
    this.pricePlanDetails = pricePlanDetails;
    return this;
  }

  /**
   * Get pricePlanDetails
   * @return pricePlanDetails
   */
  @javax.annotation.Nonnull
  public PricePlanDetails getPricePlanDetails() {
    return pricePlanDetails;
  }

  public void setPricePlanDetails(@javax.annotation.Nonnull PricePlanDetails pricePlanDetails) {
    this.pricePlanDetails = pricePlanDetails;
  }


  public CalculateRevenueResponse revenueInfo(@javax.annotation.Nonnull List<RevenueInfo> revenueInfo) {
    this.revenueInfo = revenueInfo;
    return this;
  }

  public CalculateRevenueResponse addRevenueInfoItem(RevenueInfo revenueInfoItem) {
    if (this.revenueInfo == null) {
      this.revenueInfo = new ArrayList<>();
    }
    this.revenueInfo.add(revenueInfoItem);
    return this;
  }

  /**
   * Get revenueInfo
   * @return revenueInfo
   */
  @javax.annotation.Nonnull
  public List<RevenueInfo> getRevenueInfo() {
    return revenueInfo;
  }

  public void setRevenueInfo(@javax.annotation.Nonnull List<RevenueInfo> revenueInfo) {
    this.revenueInfo = revenueInfo;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CalculateRevenueResponse calculateRevenueResponse = (CalculateRevenueResponse) o;
    return Objects.equals(this.currency, calculateRevenueResponse.currency) &&
        Objects.equals(this.usageLookupRange, calculateRevenueResponse.usageLookupRange) &&
        Objects.equals(this.pricePlanDetails, calculateRevenueResponse.pricePlanDetails) &&
        Objects.equals(this.revenueInfo, calculateRevenueResponse.revenueInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, usageLookupRange, pricePlanDetails, revenueInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CalculateRevenueResponse {\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    usageLookupRange: ").append(toIndentedString(usageLookupRange)).append("\n");
    sb.append("    pricePlanDetails: ").append(toIndentedString(pricePlanDetails)).append("\n");
    sb.append("    revenueInfo: ").append(toIndentedString(revenueInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("currency");
    openapiFields.add("usageLookupRange");
    openapiFields.add("pricePlanDetails");
    openapiFields.add("revenueInfo");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("currency");
    openapiRequiredFields.add("pricePlanDetails");
    openapiRequiredFields.add("revenueInfo");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CalculateRevenueResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CalculateRevenueResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CalculateRevenueResponse is not found in the empty JSON string", CalculateRevenueResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CalculateRevenueResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CalculateRevenueResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CalculateRevenueResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
      // validate the optional field `usageLookupRange`
      if (jsonObj.get("usageLookupRange") != null && !jsonObj.get("usageLookupRange").isJsonNull()) {
        UsageLookupRange.validateJsonElement(jsonObj.get("usageLookupRange"));
      }
      // validate the required field `pricePlanDetails`
      PricePlanDetails.validateJsonElement(jsonObj.get("pricePlanDetails"));
      // ensure the json data is an array
      if (!jsonObj.get("revenueInfo").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `revenueInfo` to be an array in the JSON string but got `%s`", jsonObj.get("revenueInfo").toString()));
      }

      JsonArray jsonArrayrevenueInfo = jsonObj.getAsJsonArray("revenueInfo");
      // validate the required field `revenueInfo` (array)
      for (int i = 0; i < jsonArrayrevenueInfo.size(); i++) {
        RevenueInfo.validateJsonElement(jsonArrayrevenueInfo.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CalculateRevenueResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CalculateRevenueResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CalculateRevenueResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CalculateRevenueResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CalculateRevenueResponse>() {
           @Override
           public void write(JsonWriter out, CalculateRevenueResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CalculateRevenueResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CalculateRevenueResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CalculateRevenueResponse
   * @throws IOException if the JSON string is invalid with respect to CalculateRevenueResponse
   */
  public static CalculateRevenueResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CalculateRevenueResponse.class);
  }

  /**
   * Convert an instance of CalculateRevenueResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

