/*
 * Togai Apis
 * APIs for Togai App
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engg@togai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.togai.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.togai.client.JSON;

/**
 * EventPipelineInfoRevenueDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class EventPipelineInfoRevenueDetails implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_USAGE_METER_ID = "usageMeterId";
  @SerializedName(SERIALIZED_NAME_USAGE_METER_ID)
  @javax.annotation.Nonnull
  private String usageMeterId;

  public static final String SERIALIZED_NAME_REVENUE_BASE_CURRENCY = "revenueBaseCurrency";
  @SerializedName(SERIALIZED_NAME_REVENUE_BASE_CURRENCY)
  @javax.annotation.Nonnull
  private BigDecimal revenueBaseCurrency;

  public static final String SERIALIZED_NAME_REVENUE_INVOICE_CURRENCY = "revenueInvoiceCurrency";
  @SerializedName(SERIALIZED_NAME_REVENUE_INVOICE_CURRENCY)
  @javax.annotation.Nonnull
  private BigDecimal revenueInvoiceCurrency;

  public EventPipelineInfoRevenueDetails() {
  }

  public EventPipelineInfoRevenueDetails usageMeterId(@javax.annotation.Nonnull String usageMeterId) {
    this.usageMeterId = usageMeterId;
    return this;
  }

  /**
   * Get usageMeterId
   * @return usageMeterId
   */
  @javax.annotation.Nonnull
  public String getUsageMeterId() {
    return usageMeterId;
  }

  public void setUsageMeterId(@javax.annotation.Nonnull String usageMeterId) {
    this.usageMeterId = usageMeterId;
  }


  public EventPipelineInfoRevenueDetails revenueBaseCurrency(@javax.annotation.Nonnull BigDecimal revenueBaseCurrency) {
    this.revenueBaseCurrency = revenueBaseCurrency;
    return this;
  }

  /**
   * Get revenueBaseCurrency
   * @return revenueBaseCurrency
   */
  @javax.annotation.Nonnull
  public BigDecimal getRevenueBaseCurrency() {
    return revenueBaseCurrency;
  }

  public void setRevenueBaseCurrency(@javax.annotation.Nonnull BigDecimal revenueBaseCurrency) {
    this.revenueBaseCurrency = revenueBaseCurrency;
  }


  public EventPipelineInfoRevenueDetails revenueInvoiceCurrency(@javax.annotation.Nonnull BigDecimal revenueInvoiceCurrency) {
    this.revenueInvoiceCurrency = revenueInvoiceCurrency;
    return this;
  }

  /**
   * Get revenueInvoiceCurrency
   * @return revenueInvoiceCurrency
   */
  @javax.annotation.Nonnull
  public BigDecimal getRevenueInvoiceCurrency() {
    return revenueInvoiceCurrency;
  }

  public void setRevenueInvoiceCurrency(@javax.annotation.Nonnull BigDecimal revenueInvoiceCurrency) {
    this.revenueInvoiceCurrency = revenueInvoiceCurrency;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventPipelineInfoRevenueDetails eventPipelineInfoRevenueDetails = (EventPipelineInfoRevenueDetails) o;
    return Objects.equals(this.usageMeterId, eventPipelineInfoRevenueDetails.usageMeterId) &&
        Objects.equals(this.revenueBaseCurrency, eventPipelineInfoRevenueDetails.revenueBaseCurrency) &&
        Objects.equals(this.revenueInvoiceCurrency, eventPipelineInfoRevenueDetails.revenueInvoiceCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(usageMeterId, revenueBaseCurrency, revenueInvoiceCurrency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventPipelineInfoRevenueDetails {\n");
    sb.append("    usageMeterId: ").append(toIndentedString(usageMeterId)).append("\n");
    sb.append("    revenueBaseCurrency: ").append(toIndentedString(revenueBaseCurrency)).append("\n");
    sb.append("    revenueInvoiceCurrency: ").append(toIndentedString(revenueInvoiceCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("usageMeterId");
    openapiFields.add("revenueBaseCurrency");
    openapiFields.add("revenueInvoiceCurrency");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("usageMeterId");
    openapiRequiredFields.add("revenueBaseCurrency");
    openapiRequiredFields.add("revenueInvoiceCurrency");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EventPipelineInfoRevenueDetails
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EventPipelineInfoRevenueDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EventPipelineInfoRevenueDetails is not found in the empty JSON string", EventPipelineInfoRevenueDetails.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EventPipelineInfoRevenueDetails.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EventPipelineInfoRevenueDetails` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EventPipelineInfoRevenueDetails.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("usageMeterId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `usageMeterId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("usageMeterId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EventPipelineInfoRevenueDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EventPipelineInfoRevenueDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EventPipelineInfoRevenueDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EventPipelineInfoRevenueDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<EventPipelineInfoRevenueDetails>() {
           @Override
           public void write(JsonWriter out, EventPipelineInfoRevenueDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EventPipelineInfoRevenueDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EventPipelineInfoRevenueDetails given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EventPipelineInfoRevenueDetails
   * @throws IOException if the JSON string is invalid with respect to EventPipelineInfoRevenueDetails
   */
  public static EventPipelineInfoRevenueDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EventPipelineInfoRevenueDetails.class);
  }

  /**
   * Convert an instance of EventPipelineInfoRevenueDetails to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

