/*
 * Togai Apis
 * APIs for Togai App
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engg@togai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.togai.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets RateCardBundleAggregation
 */
@JsonAdapter(RateCardBundleAggregation.Adapter.class)
public enum RateCardBundleAggregation {
  
  MAX("MAX"),
  
  MIN("MIN"),
  
  SUM("SUM"),
  
  AVG("AVG");

  private String value;

  RateCardBundleAggregation(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RateCardBundleAggregation fromValue(String value) {
    for (RateCardBundleAggregation b : RateCardBundleAggregation.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<RateCardBundleAggregation> {
    @Override
    public void write(final JsonWriter jsonWriter, final RateCardBundleAggregation enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public RateCardBundleAggregation read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return RateCardBundleAggregation.fromValue(value);
    }
  }
}

