/*
 * Togai Apis
 * APIs for Togai App
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engg@togai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.togai.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.togai.client.models.PriceType;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.togai.client.JSON;

/**
 * Represents a pricing priceType (rates + slabs) for usage price plan
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class Slab implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  @javax.annotation.Nonnull
  private Integer order;

  public static final String SERIALIZED_NAME_START_AFTER = "startAfter";
  @SerializedName(SERIALIZED_NAME_START_AFTER)
  @javax.annotation.Nonnull
  private BigDecimal startAfter;

  public static final String SERIALIZED_NAME_PRICE_TYPE = "priceType";
  @SerializedName(SERIALIZED_NAME_PRICE_TYPE)
  @javax.annotation.Nonnull
  private PriceType priceType;

  public static final String SERIALIZED_NAME_SLAB_CONFIG = "slabConfig";
  @SerializedName(SERIALIZED_NAME_SLAB_CONFIG)
  @javax.annotation.Nullable
  private Map<String, String> slabConfig = new HashMap<>();

  public Slab() {
  }

  public Slab order(@javax.annotation.Nonnull Integer order) {
    this.order = order;
    return this;
  }

  /**
   * Get order
   * minimum: 1
   * maximum: 10
   * @return order
   */
  @javax.annotation.Nonnull
  public Integer getOrder() {
    return order;
  }

  public void setOrder(@javax.annotation.Nonnull Integer order) {
    this.order = order;
  }


  public Slab startAfter(@javax.annotation.Nonnull BigDecimal startAfter) {
    this.startAfter = startAfter;
    return this;
  }

  /**
   * Get startAfter
   * @return startAfter
   */
  @javax.annotation.Nonnull
  public BigDecimal getStartAfter() {
    return startAfter;
  }

  public void setStartAfter(@javax.annotation.Nonnull BigDecimal startAfter) {
    this.startAfter = startAfter;
  }


  public Slab priceType(@javax.annotation.Nonnull PriceType priceType) {
    this.priceType = priceType;
    return this;
  }

  /**
   * Get priceType
   * @return priceType
   */
  @javax.annotation.Nonnull
  public PriceType getPriceType() {
    return priceType;
  }

  public void setPriceType(@javax.annotation.Nonnull PriceType priceType) {
    this.priceType = priceType;
  }


  public Slab slabConfig(@javax.annotation.Nullable Map<String, String> slabConfig) {
    this.slabConfig = slabConfig;
    return this;
  }

  public Slab putSlabConfigItem(String key, String slabConfigItem) {
    if (this.slabConfig == null) {
      this.slabConfig = new HashMap<>();
    }
    this.slabConfig.put(key, slabConfigItem);
    return this;
  }

  /**
   * Get slabConfig
   * @return slabConfig
   */
  @javax.annotation.Nullable
  public Map<String, String> getSlabConfig() {
    return slabConfig;
  }

  public void setSlabConfig(@javax.annotation.Nullable Map<String, String> slabConfig) {
    this.slabConfig = slabConfig;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Slab slab = (Slab) o;
    return Objects.equals(this.order, slab.order) &&
        Objects.equals(this.startAfter, slab.startAfter) &&
        Objects.equals(this.priceType, slab.priceType) &&
        Objects.equals(this.slabConfig, slab.slabConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(order, startAfter, priceType, slabConfig);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Slab {\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    startAfter: ").append(toIndentedString(startAfter)).append("\n");
    sb.append("    priceType: ").append(toIndentedString(priceType)).append("\n");
    sb.append("    slabConfig: ").append(toIndentedString(slabConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("order");
    openapiFields.add("startAfter");
    openapiFields.add("priceType");
    openapiFields.add("slabConfig");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("order");
    openapiRequiredFields.add("startAfter");
    openapiRequiredFields.add("priceType");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Slab
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Slab.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Slab is not found in the empty JSON string", Slab.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Slab.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Slab` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Slab.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `priceType`
      PriceType.validateJsonElement(jsonObj.get("priceType"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Slab.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Slab' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Slab> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Slab.class));

       return (TypeAdapter<T>) new TypeAdapter<Slab>() {
           @Override
           public void write(JsonWriter out, Slab value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Slab read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Slab given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Slab
   * @throws IOException if the JSON string is invalid with respect to Slab
   */
  public static Slab fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Slab.class);
  }

  /**
   * Convert an instance of Slab to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

