/*
 * Togai Apis
 * APIs for Togai App
 *
 * The version of the OpenAPI document: 1.0
 * Contact: engg@togai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.togai.client.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.togai.client.models.PlanOverride;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.togai.client.JSON;

/**
 * UpdatePricingScheduleResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class UpdatePricingScheduleResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ACCOUNT_ID = "accountId";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_ID)
  private String accountId;

  public static final String SERIALIZED_NAME_ACCOUNT_NAME = "accountName";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NAME)
  private String accountName;

  public static final String SERIALIZED_NAME_PRICING_SCHEDULES = "pricingSchedules";
  @SerializedName(SERIALIZED_NAME_PRICING_SCHEDULES)
  private List<PlanOverride> pricingSchedules = new ArrayList<>();

  public UpdatePricingScheduleResponse() {
  }

  public UpdatePricingScheduleResponse accountId(String accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * Identifier of the account
   * @return accountId
  **/
  @javax.annotation.Nonnull

  public String getAccountId() {
    return accountId;
  }


  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }


  public UpdatePricingScheduleResponse accountName(String accountName) {
    
    this.accountName = accountName;
    return this;
  }

   /**
   * Name of the Account
   * @return accountName
  **/
  @javax.annotation.Nonnull

  public String getAccountName() {
    return accountName;
  }


  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }


  public UpdatePricingScheduleResponse pricingSchedules(List<PlanOverride> pricingSchedules) {
    
    this.pricingSchedules = pricingSchedules;
    return this;
  }

  public UpdatePricingScheduleResponse addPricingSchedulesItem(PlanOverride pricingSchedulesItem) {
    this.pricingSchedules.add(pricingSchedulesItem);
    return this;
  }

   /**
   * Get pricingSchedules
   * @return pricingSchedules
  **/
  @javax.annotation.Nonnull

  public List<PlanOverride> getPricingSchedules() {
    return pricingSchedules;
  }


  public void setPricingSchedules(List<PlanOverride> pricingSchedules) {
    this.pricingSchedules = pricingSchedules;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePricingScheduleResponse updatePricingScheduleResponse = (UpdatePricingScheduleResponse) o;
    return Objects.equals(this.accountId, updatePricingScheduleResponse.accountId) &&
        Objects.equals(this.accountName, updatePricingScheduleResponse.accountName) &&
        Objects.equals(this.pricingSchedules, updatePricingScheduleResponse.pricingSchedules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, accountName, pricingSchedules);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePricingScheduleResponse {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    pricingSchedules: ").append(toIndentedString(pricingSchedules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accountId");
    openapiFields.add("accountName");
    openapiFields.add("pricingSchedules");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("accountId");
    openapiRequiredFields.add("accountName");
    openapiRequiredFields.add("pricingSchedules");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UpdatePricingScheduleResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UpdatePricingScheduleResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdatePricingScheduleResponse is not found in the empty JSON string", UpdatePricingScheduleResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!UpdatePricingScheduleResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdatePricingScheduleResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdatePricingScheduleResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("accountId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accountId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountId").toString()));
      }
      if (!jsonObj.get("accountName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accountName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountName").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("pricingSchedules").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `pricingSchedules` to be an array in the JSON string but got `%s`", jsonObj.get("pricingSchedules").toString()));
      }

      JsonArray jsonArraypricingSchedules = jsonObj.getAsJsonArray("pricingSchedules");
      // validate the required field `pricingSchedules` (array)
      for (int i = 0; i < jsonArraypricingSchedules.size(); i++) {
        PlanOverride.validateJsonObject(jsonArraypricingSchedules.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdatePricingScheduleResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdatePricingScheduleResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdatePricingScheduleResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdatePricingScheduleResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdatePricingScheduleResponse>() {
           @Override
           public void write(JsonWriter out, UpdatePricingScheduleResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdatePricingScheduleResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UpdatePricingScheduleResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UpdatePricingScheduleResponse
  * @throws IOException if the JSON string is invalid with respect to UpdatePricingScheduleResponse
  */
  public static UpdatePricingScheduleResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdatePricingScheduleResponse.class);
  }

 /**
  * Convert an instance of UpdatePricingScheduleResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

